import { Injectable } from '@angular/core';

import Product from '../../models/product'
import FilterModel from 'src/app/models/filterModel';

@Injectable({
  providedIn: 'root'
})
export class ProductService {


  getProduct() {
    return this.products
  }

  filter() {
    return this.filters
  }
  nav() {
    return this.navbar
  }


  public products: Array<Product> = [
    {
      image: '../../../assets/saat.jpg',
      gender: "female",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "20%",
      discount_price: "1384",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "20%",
      discount_price: "1384",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "20%",
      discount_price: "1384",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "20%",
      discount_price: "1384",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
    {
      image: '../../../assets/saat.jpg',
      gender: "kadın",
      brand: "Emporio Armani",
      model: "AR11231 ",
      glass_property: "organik",
      price: "1730",
      discount: "",
      discount_price: "",
      discount_image: "../../../assets/20-icon.jpg",
      case_shape: "yuvarlak",
      dial_color: "lacivert",
      glass_type: "organik",
      strap_type: "deri",
      strap_color: "lacivert",
      running_style: "analog",
      waterproof: "3 ATM"
    },
  ]

  public filters: Array<FilterModel> = [
    {
      title: "Cinsiyet",
      filter_field: "genders",
      items: [
        { key: 'Erkek', value: 'male' },
        { key: 'Kadın', value: 'female' }
      ]
    },
    {
      title: "Marka",
      filter_field: "brands",
      items: [
        { key: "Adidas", value: "adidas" },
        { key: "Calvin Klein", value: "ck" },
        { key: "Casio", value: "casio" },
        { key: "Diesel", value: "diesel" },
        { key: "Dkny", value: "dkny" },
        { key: "Emporio Armani", value: "ea" },
        { key: "Esprit", value: "esprit" },
        { key: "Essence", value: "essence" },
      ]
    },
    {
      title: "Cam Özelliği",
      filter_field: "glass_properties",
      items: [
        { key: "Safir", value: "sapphire" },
        { key: "Kristal", value: "crystal" },
        { key: "Organik", value: "organic" }
      ]
    },
    {
      title: "Fiyat Aralığı",
      filter_field: "price_ranges",
      items: [
        { key: "50 TL - 100 TL", value: "" },
        { key: "100 TL - 250 TL", value: "" },
        { key: "250 TL - 500 TL", value: "" },
        { key: "500 TL - 750 TL", value: "" },
        { key: "750 TL - 1000 TL", value: "" },
        { key: "1.000 TL - 1.500 TL", value: "" },
        { key: "1.500 TL - 2.000 TL", value: "" },
        { key: "2.000 TL - 3.000 TL", value: "" },
        { key: "3.000 TL - 5.000 TL", value: "" },
        { key: "5.000 TL - 10.000 TL", value: "" },
        { key: "10.000 TL - 20.000 TL", value: "" },
        { key: "20.000 TL - 50.000 TL", value: "" },
      ]
    },
    {
      title: "Kasa Şekli",
      filter_field: "case_types",
      items: [
        { key: "Yuvarlak", value: "round" },
        { key: "Köşeli", value: "edged" }
      ]
    },
    {
      title: "Kadran Rengi",
      filter_field: "dial_colors",
      items: [
        { key: "Beyaz", value: "white" },
        { key: "Kahverengi", value: "brown" },
        { key: "Gri", value: "grey" },
        { key: "Bicolor", value: "bicolor" }
      ]
    },
    {
      title: "Cam Tipi",
      filter_field: "glass_types",
      items: [
        { key: "Safir Kristal", value: "sapphire crystal" },
        { key: "Mineral", value: "mineral" },
        { key: "Organik", value: "organic" }
      ]
    },
    {
      title: "Kayış Tipi",
      filter_field: "strap_types",
      items: [
        { key: "Çelik", value: "steel" },
        { key: "Deri", value: "leather" },
        { key: "Metal", value: "metal" },
        { key: "Hasır", value: "wicker" },
        { key: "Silikon", value: "silicone" }
      ]
    },
    {
      title: "Kayış Rengi",
      filter_field: "strap_colors",
      items: [
        { key: "Siyah", value: "black" },
        { key: "Beyaz", value: "white" },
        { key: "Yeşil", value: "green" },
        { key: "Mor", value: "purple" },
        { key: "Sarı", value: "yellow" },
        { key: "Kahverengi", value: "brown" }
      ]
    },
    {
      title: "Çalışma Şekli",
      filter_field: "running_style",
      items: [
        { key: "Analog", value: "analog" },
        { key: "Analog / Dijital", value: "analog/digital" },
        { key: "Dijital", value: "digital" }
      ]
    },
    {
      title: "Su Geçirmezlik",
      filter_field: "waterproof",
      items: [
        { key: "atm", value: "" },
        { key: "10 atm", value: "" },
        { key: "100 atm", value: "" },
        { key: "20 atm", value: "" },
        { key: "200 atm", value: "" },
      ]
    },
  ]

  public navbar = [


    { key: "anasayfa" },
    { key: "kadın kol saatleri" },
    { key: "erkek kol saatleri" },
    { key: "markalar" },
    { key: "fırsat ürünleri" },
    { key: "haftanın ürünleri" },


  ]


  constructor() { }


}
